# Generated by Django 5.2.11 on 2026-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('video_url', models.CharField(max_length=500, verbose_name='视频文件路径')),
                ('cover_image', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图片路径')),
                ('match_date', models.DateField(verbose_name='比赛日期')),
                ('teams', models.CharField(max_length=100, verbose_name='对阵球队')),
                ('views', models.IntegerField(default=0, verbose_name='观看次数')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '精彩回放',
                'verbose_name_plural': '精彩回放',
                'db_table': 'highlight',
                'ordering': ['-match_date', '-created_at'],
            },
        ),
    ]
