# Generated by Django 5.2.11 on 2026-02-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
    ]
