# Generated by Django 5.2.11 on 2026-04-05 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_alter_highlight_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='favorites',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.CreateModel(
            name='HighlightFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highlights.highlight', verbose_name='视频')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频收藏',
                'verbose_name_plural': '视频收藏',
                'db_table': 'highlight_favorite',
                'indexes': [models.Index(fields=['highlight'], name='highlight_f_highlig_d661a2_idx'), models.Index(fields=['user'], name='highlight_f_user_id_716349_idx')],
                'unique_together': {('user', 'highlight')},
            },
        ),
        migrations.CreateModel(
            name='HighlightLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highlights.highlight', verbose_name='视频')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频点赞',
                'verbose_name_plural': '视频点赞',
                'db_table': 'highlight_like',
                'indexes': [models.Index(fields=['highlight'], name='highlight_l_highlig_93ef46_idx'), models.Index(fields=['user'], name='highlight_l_user_id_bd48f8_idx')],
                'unique_together': {('user', 'highlight')},
            },
        ),
    ]
