# Generated by Django 5.2.11 on 2026-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='球员姓名')),
                ('team', models.CharField(max_length=100, verbose_name='所属球队')),
                ('position', models.CharField(max_length=50, verbose_name='位置')),
                ('avatar', models.TextField(blank=True, null=True, verbose_name='头像')),
                ('ranking', models.IntegerField(default=0, verbose_name='排名')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='评分(星级)')),
                ('points_per_game', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='场均得分')),
                ('rebounds_per_game', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='场均篮板')),
                ('assists_per_game', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='场均助攻')),
                ('steals_per_game', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='场均抢断')),
                ('blocks_per_game', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='场均盖帽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '球员',
                'verbose_name_plural': '球员',
                'db_table': 'player',
                'ordering': ['ranking'],
            },
        ),
    ]
