# Generated by Django 5.2.11 on 2026-03-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='球星名字')),
                ('source_type', models.CharField(choices=[('article', '文章'), ('product', '商品'), ('video', '视频'), ('comment', '评论')], max_length=20, verbose_name='来源类型')),
                ('source_id', models.IntegerField(verbose_name='来源ID')),
                ('mention_count', models.IntegerField(default=1, verbose_name='提及次数')),
                ('sentiment', models.CharField(choices=[('positive', '正面'), ('negative', '负面'), ('neutral', '中性')], default='neutral', max_length=20, verbose_name='情感')),
                ('context', models.TextField(blank=True, null=True, verbose_name='上下文片段')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, verbose_name='提取时间')),
            ],
            options={
                'verbose_name': '球星提及记录',
                'verbose_name_plural': '球星提及记录',
                'db_table': 'player_mention',
                'indexes': [models.Index(fields=['player_name', 'extracted_at'], name='player_ment_player__fd545b_idx'), models.Index(fields=['source_type', 'source_id'], name='player_ment_source__ffb90e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='球星名字')),
                ('time_period', models.CharField(choices=[('daily', '日'), ('weekly', '周'), ('monthly', '月'), ('quarterly', '季度'), ('yearly', '年')], max_length=20, verbose_name='时间周期')),
                ('period_value', models.CharField(max_length=20, verbose_name='周期值')),
                ('article_mentions', models.IntegerField(default=0, verbose_name='文章提及数')),
                ('product_mentions', models.IntegerField(default=0, verbose_name='商品提及数')),
                ('video_mentions', models.IntegerField(default=0, verbose_name='视频提及数')),
                ('comment_mentions', models.IntegerField(default=0, verbose_name='评论提及数')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='综合评分')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '球星热度统计',
                'verbose_name_plural': '球星热度统计',
                'db_table': 'player_popularity',
                'indexes': [models.Index(fields=['time_period', 'period_value', 'ranking'], name='player_popu_time_pe_36b860_idx')],
                'unique_together': {('player_name', 'time_period', 'period_value')},
            },
        ),
    ]
